export const metadata = {
  title: 'Next.js',
  description: 'Generated by nemsimedia.ma',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
